apiVersion: batch/v1
kind: Job
metadata:
  name: random-error-seq-job
spec:
  completions: 3 # How many times we want to perform the job successfully
  backoffLimit: 50
  template:
    # Hier comes the Pod definition
    spec:
      containers:
        - name: random-error
          image: kodekloud/random-error
      restartPolicy: Never
