apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  completions: 3 # How many times we want to perform the job successfully
  template:
    # Hier comes the Pod definition
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: ["expr", "3", "+", "5"]
      restartPolicy: Never
