apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-recreate-dep
  namespace: demo-strategy
spec:
  replicas: 3
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: demo-recreate-dep
  template:
    metadata:
      labels:
        app: demo-recreate-dep
    spec:
      containers:
        - image: kodekloud/webapp-color:v1
          name: webapp-color
