---
apiVersion: v1
kind: Pod
metadata:
  name: required-1-match
spec:
  containers:
    - image: nginx
      name: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "my_label"
              operator: In
              values: ["something"]
---
apiVersion: v1
kind: Pod
metadata:
  name: required-2-no-match
spec:
  containers:
    - image: nginx
      name: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "my_label"
              operator: In
              values: ["something2"]