---
apiVersion: v1
kind: Pod
metadata:
  name: bee
spec:
  tolerations:
    - key: "mykey"
      operator: "Equal"
      value: "something"
      effect: "NoSchedule"
  containers:
    - image: nginx
      name: nginx