apiVersion: v1
kind: Pod
metadata:
  name: demo-6-cm-2
spec:
  restartPolicy: "Never"
  containers:
    - image: kindjozsef/greeting
      name: greetingcontainer
      envFrom:
        - configMapRef:
            name: my-configmap-2
