---
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - image: nginx
      name: test
      command:
        - sh
        - -c
        - |
          echo "#!/bin/sh" > /tmp/script.sh
          echo "while true; do curl -s -f \$1 && echo || echo "Error"; sleep 1; done" >> /tmp/script.sh
          chmod +x /tmp/script.sh
          sleep 3600
