---
apiVersion: v1
kind: Pod
metadata:
  name: root-ubuntu
spec:
  containers:
    - image: ubuntu
      name: root-ubuntu
      command: ["sh", "-c", "sleep 3000"]
---
apiVersion: v1
kind: Pod
metadata:
  name: non-root-ubuntu-1
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - image: ubuntu
      name: non-root-ubuntu-1
      command: ["sh", "-c", "sleep 3000"]
      securityContext:
        runAsUser: 2000
---
apiVersion: v1
kind: Pod
metadata:
  name: non-root-ubuntu-2
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - image: ubuntu
      command: ["sh", "-c", "sleep 3000"]
      securityContext:
        capabilities:
          add: ["SYS_TIME"]
      name: non-root-ubuntu-2