---
apiVersion: v1
kind: Pod
metadata:
  name: rl-demo
spec:
  containers:
    - image: polinux/stress
      name: mem-stress
      command: ["sh", "-c", "sleep 3600"]
      args: ["--vm", "1", "--vm-bytes", "15M", "--vm-hang", "1", "--cpu", "50"]
      command: ["stress"]
      resources:
        limits:
          memory: 25Mi
          cpu: 100m